### ISSUE TITLE
Pre-Renewal Godly item

### ISSUE THREAD

**Issue by kyeme** [zackdreaver/ROenglishPRE#2]
Sleipnir
        bonus bMdef,10;
        bonus bMaxHPrate,20; <--  10% on description
        bonus bMaxSPrate,20; <--  10% on description
        bonus bSPrecovRate,15;
        bonus bSpeedRate,25;

Brysinggamen
        bonus bStr,6;
        bonus bAgi,6;
        bonus bVit,6;
        bonus bInt,6;
        bonus bLuk,10;
        bonus bMdef,5; <-- Missing

Mjolnir:
        bonus bAtkEle,Ele_Wind;
        bonus bDex,40; <-- +50 on description
        bonus bStr,15; <-- +20 on description
        bonus bAspdRate,10;
        bonus bUnbreakableWeapon,0;

**Comment by zackdreaver** [comment]
Thanks for reporting,
pre-re repo desc kinda a mess right now because it's using iro classic, which are mixed between renewal and pre-renewal, and they tend to be missing a lot of desc..
