### ISSUE TITLE
Skill/Attack range will not walk into range when 1 cell out of range.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [zackdreaver/ROenglishPRE#5]
Hi, still having navigation problems with attack range for both skills and weapon attacks.

Envenom Range 2.
Spawn monster 1721, move 3 cell away, cast the skill.
Character does not navigate 1 cell into range like it should?
Try at 4 cells away or more, and it walks into range correctly and casts the skill.
Try at 2 or 1 it will cast the skill.

But this also happens with attacks not just skills.
At 2 cells away with bare hands or dagger/sword.
And at 4 with a spear.

It does appear to be client side, as the client does not send any network packets to attack.
Any ideas where to fix this?

Client: 2015-09-16aRagexe

Thanks in advance.

**Comment by zackdreaver** [comment]
I have no idea really.
I've done what i can by fixing the lua, and i haven't encountered any issue ever since.
Maybe related with diff patch, other than that, i have no clue.
