### ISSUE TITLE
Missing maps from worldviewdata files

### ISSUE THREAD

**Issue by Daegaladh** [zackdreaver/ROenglishPRE#8]
Several maps were removed in renewal (fields from rachel, veins, juno, comodo, etc..) and they're missing from the worldviewdata files in pre-renewal.

**Comment by zackdreaver** [comment]
There are no Rune Midgard maps were removed in pre-renewal,
Only new worlds+some localization maps that updated on renewal were removed.

EDIT: I'll check what's missing

**Comment by Daegaladh** [comment]
It's the other way around, there are missing maps in pre-renewal, because they're no longer used in renewal, for example ra_fild02, ra_fild07, ra_fild10, ra_fild11 and more.

**Comment by zackdreaver** [comment]
Update both renewal and prerenewal project, it should be fixed now.
List fix:
gef_fild12 = fixed
gef_fild14 = fixed
pay_fild05 = fixed
pay_fild11 = fixed
cmd_fild05 = fixed
yuno_fild05 = Not possible
yuno_fild10 = fixed
hu_fild03 = fixed
hu_fild07 = fixed
ein_fild02 = missing map preview
ein_fild10 = fixed
ra_fild02 = fixed
ra_fild07 = missing map preview
ra_fild09 = fixed
ra_fild10 = fixed
ra_fild11 = missing map preview
ra_fild13 = fixed
ve_fild05 = fixed
um_dun01 = fixed
um_dun02 = fixed
